"""empty message

Revision ID: 2098d3f0ea2b
Revises: 2aab814ecd52
Create Date: 2021-10-28 23:19:04.037592

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2098d3f0ea2b'
down_revision = '2aab814ecd52'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fav_movies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('movieID', sa.Integer(), nullable=True),
    sa.Column('username', sa.Text(), nullable=False),
    sa.Column('pub_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('entry')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entry',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=80), nullable=False),
    sa.Column('body', sa.TEXT(), nullable=False),
    sa.Column('pub_date', sa.DATETIME(), nullable=False),
    sa.Column('is_published', sa.BOOLEAN(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('fav_movies')
    # ### end Alembic commands ###
